### ISSUE TITLE
无法导入setting jar包进入as

### ISSUE THREAD

**Issue by getideas** [xinghongfei/android-studio-setting#1]

**Comment by xinghongfei** [comment]
我刚又试了一遍，可以啊，你是不哪里出错了。

**Comment by asfman** [comment]
顺便问一下 怎么还原到默认的？

**Comment by xinghongfei** [comment]
请关注我博客下面的讨论，已经回答。

**Comment by asfman** [comment]
`
![tmp](https://cloud.githubusercontent.com/assets/169468/18120015/1837c35a-6f90-11e6-9679-26b6233edfa3.png)
默认是哪一个？

**Comment by xinghongfei** [comment]
<img width="258" alt="2016-08-31 3 49 00" src="https://cloud.githubusercontent.com/assets/16009006/18120522/8b091c6a-6f92-11e6-82f4-b994aea69b62.png">
**default**

**Comment by asfman** [comment]
我的Appearance下的Theme选项只有Dracula和default,然后现在就是default 但是编辑器还是原来的颜色，系统是白色了

**Comment by asfman** [comment]
ok 原来还是在color&fonts那设置，我那列表太长 没看到，删了几个样式后看到了。麻烦你了，谢谢
