### ISSUE TITLE
导入不启用

### ISSUE THREAD

**Issue by addappcn** [xinghongfei/android-studio-setting#2]

**Comment by wu-leaf** [comment]
导入不可用，出现3个对话框提示Cannot read scheme monokai.icls  from '$ROOT_CONFIG$/colors': Unsupported color scheme version: 142
Cannot read scheme xinghongfei.icls  from '$ROOT_CONFIG$/colors': Unsupported color scheme version: 142
Cannot read scheme xinghongfei copy.icls  from '$ROOT_CONFIG$/colors': Unsupported color scheme version: 142

**Comment by wu-leaf** [comment]
升级Android studio之后
再设置下就可以了

**Comment by xinghongfei** [comment]
恭喜
