### ISSUE TITLE
AS 2.2 Pre版本

### ISSUE THREAD

**Issue by ZQiang94** [xinghongfei/android-studio-setting#3]
![image](https://cloud.githubusercontent.com/assets/7663942/18298836/1ae436f2-74ee-11e6-9a34-3d8480d438e6.png)
你好，我是2.2Pre版本，应该在哪里导入呢？找半天了   期待回复。谢谢

**Comment by ZQiang94** [comment]
已经解决了，但是各种问题，github访问变成了你的，本地的gerrit账号丢失，导致pull faile........
慎重....不过分享精神值得尊敬，thx~  但是个人觉得还是把其中能够包含个人信息的勾勾取消掉比较好~~~~

**Comment by xinghongfei** [comment]
非常抱歉，我又重现上传了一份，可以试一下。
